DeBrabander/Models/Order/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DeBrabander.Models
{
    public class Order
    {
        [Key]
        public int OrderId { get; set; }
        [DisplayName("Order nummer")]
        public int OrderNumber { get; set; }
        [DisplayFormat(DataFormatString = "{0:C}")]
        [DisplayName("Totaal prijs")]
        public double TotalPrice { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("Aangemaakt op")]
        public DateTime Date { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("Opmerking")]
        public string Annotation { get; set; }
        [DisplayName("Actief")]
        public bool Active { get; set; }
        public int CustomerId { get; set; }
        // [DisplayName] zorgt ervoor dat het aangegeven argument 
        // wordt weergegeven in de view ipv property naam
        [DisplayName("Naam")]
        public string LastName { get; set; }
        [DisplayName("Voornaam")]
        public string FirstName { get; set; }
        [NotMapped]
        [DisplayName("Naam")]
        public string FullName
        {
            get
            {
                return LastName + " " + FirstName;
            }
        }
        [DisplayName("GSM")]
        public string CellPhone { get; set; }
        [DisplayName("Email")]
        public string Email { get; set; }
        [DisplayName("Straatnaam")]
        public string StreetName { get; set; }
        [DisplayName("Huisnummer")]
        public int StreetNumber { get; set; }
        [DisplayName("Busnummer")]
        public int Box { get; set; }
        [DisplayName("Postcode")]
        public int PostalCodeNumber { get; set; }
        [DisplayName("Gemeente")]
        public string Town { get; set; }
        public virtual CustomerDeliveryAddress customerDeliveryAddress { get; set; }
        public virtual List<OrderDetail> OrderDetail { get; set; }
    }
}

DeBrabander/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DeBrabander.DAL;
using DeBrabander.Models;

namespace DeBrabander.Controllers
{
    public class OrderDetailsController : Controller
    {
        private Context db = new Context();

        // GET: OrderDetails
        public ActionResult Index()
        {
            var orderDetails = db.OrderDetails.ToList();
            return View(orderDetails);
        }

        // GET: OrderDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderDetail orderDetail = db.OrderDetails.Find(id);
            if (orderDetail == null)
            {
                return HttpNotFound();
            }
            return View(orderDetail);
        }

        // GET: OrderDetails/Create
        public ActionResult Create()
        {
            ViewBag.OrderId = new SelectList(db.Orders, "OrderId", "Annotation");
            ViewBag.VATPercId = new SelectList(db.VATs, "VATPercId", "VATPercId");
            return View();
        }

        // POST: OrderDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderDetailId,Quantity,OrderId,ProductId,ProductName,ProductCode,Description,PriceExVAT,Reprobel,Bebat,Recupel,Auvibel,Brand,CategoryId,VATPercId,TotalExVat,TotalIncVat")] OrderDetail orderDetail)
        {
            if (ModelState.IsValid)
            {
                db.OrderDetails.Add(orderDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OrderId = new SelectList(db.Orders, "OrderId", "Annotation", orderDetail.OrderId);
            ViewBag.VATPercId = new SelectList(db.VATs, "VATPercId", "VATPercId", orderDetail.VATPercId);
            return View(orderDetail);
        }

        // GET: OrderDetails/Edit/5
        public ActionResult Edit(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderDetail orderDetail = db.OrderDetails.Find(id);
            if (orderDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.OrderId = new SelectList(db.Orders, "OrderId", "Annotation", orderDetail.OrderId);
            ViewBag.VAT = new SelectList(db.VATs, "VATPercId", "VATValue");
            ViewBag.returnUrl = Request.UrlReferrer;
            return View(orderDetail);
        }

        // POST: OrderDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderDetailId,Quantity,OrderId,ProductId,ProductName,ProductCode,Description,PriceExVAT,Reprobel,Bebat,Recupel,Auvibel,Brand,CategoryId,VATPercId,TotalExVat,TotalIncVat")] OrderDetail orderDetail, string returnUrl)
        {
            Product prod = new Product();
            prod = db.Products.Find(orderDetail.ProductId);
            VAT tempod = db.VATs.Find(orderDetail.VATPercId);

            orderDetail.ProductName = prod.ProductName;
            orderDetail.TotalExVat = (orderDetail.PriceExVAT + orderDetail.Auvibel + orderDetail.Bebat + orderDetail.Recupel + orderDetail.Reprobel) * orderDetail.Quantity;
            orderDetail.TotalIncVat = orderDetail.TotalExVat * (1 + (tempod.VATValue / 100));


            if (ModelState.IsValid)
            {
                db.Entry(orderDetail).State = EntityState.Modified;
                db.SaveChanges();
                return Redirect(returnUrl);
            }
            ViewBag.OrderId = new SelectList(db.Orders, "OrderId", "Annotation", orderDetail.OrderId);
            ViewBag.VATPercId = new SelectList(db.VATs, "VATPercId", "VATPercId", orderDetail.VATPercId);
            return Redirect(returnUrl);
        }

        // GET: OrderDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderDetail orderDetail = db.OrderDetails.Find(id);
            if (orderDetail == null)
            {
                return HttpNotFound();
            }
            return View(orderDetail);
        }

        // POST: OrderDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OrderDetail orderDetail = db.OrderDetails.Find(id);
            db.OrderDetails.Remove(orderDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DeBrabander/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DeBrabander.DAL;
using DeBrabander.Models;
using DeBrabander.ViewModels.Orders;
using DeBrabander.ViewModels;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using PagedList;

namespace DeBrabander.Controllers
{
    public class OrderBinderCreate : IModelBinder
    {
        //private Context db2 = new Context();
        public object BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
        {
            HttpContextBase objContext = controllerContext.HttpContext;
            OrderCreateViewModel obj = new OrderCreateViewModel();
            obj.order.Annotation = objContext.Request.Form["OrderInfo"];
            return obj;
        }
    }

    public class OrdersController : Controller
    {
        private Context db = new Context();

        // GET: Orders
        public ActionResult Index(string searchOrderNumber, string currentFilterOrderNumber, string searchCustomer, string currentFilterCustomer, string searchDelivery, string currentFilterDelivery, bool? searchNonActive, bool? currentFilterNonActive, int? page, string sortOrder)
        {
            // viewmodel aanmaken + vullen tijdelijke lijst
            if (searchNonActive == null) { searchNonActive = false; }
            if (currentFilterNonActive == null) { currentFilterNonActive = false; }
            OrderIndexViewModel oivm = new OrderIndexViewModel();
            var orders = from o in db.Orders select o;
            Order order = new Order();

            
            ViewBag.OrderSortParm = String.IsNullOrEmpty(sortOrder) ? "order_asc" : "";
            ViewBag.CustomerSortParm = sortOrder == "cust" ? "cust_desc" : "cust";


            if (searchCustomer != null || searchOrderNumber != null)
            {
                page = 1;
            }
            else
            {
                searchOrderNumber = currentFilterOrderNumber;
                searchCustomer = currentFilterCustomer;
                searchDelivery = currentFilterDelivery;
                searchNonActive = currentFilterNonActive;
            }
            ViewBag.CurrentFilterQuotation = searchOrderNumber;
            ViewBag.CurrentFilterCustomer = searchCustomer;
            ViewBag.CurrentFilterDelivery = searchDelivery;
            ViewBag.CurrentFilterNonActive = searchNonActive;


            if (!String.IsNullOrEmpty(searchOrderNumber))
            {
                orders = orders.Where(o => o.OrderNumber.ToString().Contains(searchOrderNumber));
            }
            if (!String.IsNullOrEmpty(searchCustomer))
            {
                orders = orders.Where(o => o.LastName.ToUpper().Contains(searchCustomer.ToUpper()) || o.FirstName.ToUpper().Contains(searchCustomer.ToUpper()));
            }
            if (!string.IsNullOrEmpty(searchDelivery))
            {
                orders = orders.Where(o => o.customerDeliveryAddress.DeliveryAddressInfo.ToUpper().Contains(searchDelivery.ToUpper()) || o.customerDeliveryAddress.StreetName.ToUpper().Contains(searchDelivery.ToUpper()) || o.customerDeliveryAddress.Town.ToUpper().Contains(searchDelivery.ToUpper()));
            }


            switch (sortOrder)
            {
                case "order_asc":
                    orders = orders.OrderBy(o => o.OrderNumber);
                    break;
                case "cust_desc":
                    orders = orders.OrderByDescending(o => o.LastName);
                    break;
                case "cust":
                    orders = orders.OrderBy(o => o.LastName);
                    break;
                default:
                    orders = orders.OrderByDescending(o => o.OrderNumber);
                    break;
            }

            var userDefinedInfo = db.UserDefinedSettings.Find(1);
            int pageSize = userDefinedInfo.IndexResultLength;
            int pageNumber = (page ?? 1);

            if (searchNonActive == false || searchNonActive == null)
            {
                orders = orders.Where(o => o.Active.Equals(true));
            }


            //ViewBag.Quotations = quotations.ToPagedList(pageNumber, pageSize);
            oivm.orders = orders.ToPagedList(pageNumber, pageSize);

            return View(oivm);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create(string sortOrder, string searchStringName, string searchStringTown, string currentFilterName, string currentFilterTown, int? page)
        {
            // quotation viewmodel + ipaged list users aanmaken + nieuwe quotation voor default stuff
            OrderCreateViewModel ocvm = new OrderCreateViewModel();
            var customerList = from a in db.Customers select a;
            Order order = new Order();

            DefaultOrderInfo(order);

            ocvm.order = order;


            //zoeken / sorteren / paging
            //sorteren  default op "name_desc" 
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.TownSortParm = sortOrder == "town" ? "town_desc" : "town";


            // als zoeken leeg is pagina 1 anders 
            if (searchStringTown != null || searchStringName != null)
            {
                page = 1;
            }
            else
            {
                searchStringName = currentFilterName;
                searchStringTown = currentFilterTown;
            }
            ViewBag.CurrentFilterName = searchStringName;
            ViewBag.CurrentFilterTown = searchStringTown;



            // zoekvelden toepassen op klantenlijst
            //zoeken op naam (voor of achter en/of gemeente)           
            if (!String.IsNullOrEmpty(searchStringTown))
            {
                customerList = customerList.Where(s => s.Address.Town.ToUpper().Contains(searchStringTown.ToUpper()));
            }

            // zoeken op postalcode
            if (!String.IsNullOrEmpty(searchStringName))
            {
                customerList = customerList.Where(s => s.LastName.ToUpper().Contains(searchStringName.ToUpper()) ||
                s.FirstName.ToUpper().Contains(searchStringName.ToUpper()));
            }


            switch (sortOrder)
            {
                case "name_desc":
                    customerList = customerList.OrderByDescending(s => s.LastName);
                    break;
                case "town":
                    customerList = customerList.OrderBy(s => s.Address.Town);
                    break;
                case "town_desc":
                    customerList = customerList.OrderByDescending(s => s.Address.Town);
                    break;
                default:
                    customerList = customerList.OrderBy(s => s.LastName);
                    break;
            }

            var userDefinedInfo = db.UserDefinedSettings.Find(1);
            int pageSize = userDefinedInfo.DetailsResultLength;
            int pageNumber = (page ?? 1);

            ocvm.customers = customerList.ToPagedList(pageNumber, pageSize);


            return View(ocvm);
        }

        private Order DefaultOrderInfo(Order order)
        {
            //basis info invullen in order
            //ophalen van lijst orders voor vinden van laatste ordernummer en dan +1 
            var listOrders = new List<Order>();
            listOrders = db.Orders.ToList();
            var userSettings = db.UserDefinedSettings.Find(1);
            

            int maxOrdernumber = 1;
            order.OrderNumber = maxOrdernumber;
            if (listOrders.Count != 0)
            {
                maxOrdernumber = listOrders.Max(o => o.OrderNumber);
                order.OrderNumber = maxOrdernumber + 1;
            }
            order.Active = true;
            order.Date = DateTime.Now;            

            return order;
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SubmitButton(Name ="CreateOrder")]
        public ActionResult Create([ModelBinder(typeof(OrderBinderCreate))]  OrderCreateViewModel ocvm, string[] DeliveryID)
        {
            if (ModelState.IsValid)
            {
                //aanmaken van quotation / customerdeliveryaddress en customer
                Order order  = new Order();
                CustomerDeliveryAddress cda = new CustomerDeliveryAddress();
                Customer cus = new Customer();

                //ophalen van customerDeliveryAddressID vanuit de array
                // eventueel nog test inbouwen voor lengte van array (check dat ze niet meer als 1 veld selecteren)
                int DeliveryId = 1;
                if (DeliveryID.Length == 1)
                {
                    DeliveryId = Int32.Parse(DeliveryID.First());
                }
                else
                {
                    return RedirectToAction("Create");
                }

                // ophalen delivery info en van daaruit customer info
                cda = db.CustomerDeliveryAddresses.Find(DeliveryId);
                cus = db.Customers.Find(cda.CustomerId);

                // invullen van de klant info in de quotation
                DefaultOrderInfo(order);
                order.FirstName = cus.FirstName;

DeBrabander/Views/Orders/AddProducts.cshtml
@model DeBrabander.ViewModels.Orders.OrderAddProductsViewModel
@using PagedList.Mvc;

@{
    ViewBag.Title = "De Brabander";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Site.css" rel="stylesheet" />
<h2>Artikelen toevoegen op order van @Model.order.FullName</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        @using (Html.BeginForm("AddProducts", "Orders", FormMethod.Get, new { id = Model.order.OrderId }))
        {
            <p>
                @Html.TextBox("searchString", ViewBag.CurrentFilterSearchString as string, new { @class = "form-control", placeholder = "Zoeken op productnaam/code", @style = "margin: 3px;" })
                @Html.DropDownList("CategoryID", (SelectList)ViewBag.CategoryID, "Categorie", new { @class = "btn btn-default dropdown-toggle" })
                @Html.TextBox("id", Model.order.OrderId, new { @class = "hidden" })
                <input type="submit" value="Zoek" class="btn btn-default" style="margin: 3px" />
            </p>
        }
    </div>

    <table class="table">
        <tr>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(Model => Model.product.ProductName).ToHtmlString(), "addProduct", new { sortOrder = ViewBag.ProductSortParm })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.ProductCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.PriceExVAT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.Category.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.Description)
            </th>
            <th>

            </th>
        </tr>

        @if (Model.products.Count() == 0)
        {
            <tr>
                <td colspan="3">Er voldoen geen artikelen aan je zoekopdracht</td>
            </tr>
        }
        else
        {
            foreach (var item in Model.products)
            {
                <tr>
                    <td>

                        @item.ProductName
                    </td>
                    <td>
                        @item.ProductCode
                    </td>
                    <td>
                        @item.Brand
                    </td>
                    <td>
                        @item.PriceExVAT
                    </td>
                    <td>
                        @item.Category.CategoryName
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        <abbr title="Artikel toevoegen">
                            <a href="@Url.Action("AddProductToOrder", "Orders", new { productId = item.ProductId, orderId = Model.order.OrderId })" class="btn btn-success">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            </a>
                        </abbr>

                    </td>

                </tr>
            }
        }
    </table>
}
<div class="row">
    <div class="col-md-2 col-md-offset-10">
        Pagina @(Model.products.PageCount < Model.products.PageNumber ? 0 : Model.products.PageNumber) van de @Model.products.PageCount
    </div>
    <div class="col-md-2 col-md-offset-10">
        @Html.PagedListPager(Model.products, page => Url.Action("AddProducts", new { @class = "pagination pagination-sm", page, currentFilterSearchString = ViewBag.CurrentFilterSearchString, currentFilterCategoryId = ViewBag.CurrentFilterCategoryId }), PagedList.PagedListRenderOptions.tomsLayout)
    </div>
</div>
<div>
    <table align="center"></table>
</div>

<br />
<br />

@if (Model != null)
{
    if (Model.order.OrderDetail != null && Model.order.OrderDetail.Count != 0)
    {
        <table class="table">
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.orderDetail.ProductName)*@
                    Artikel
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.orderDetail.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.orderDetail.Description)
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.orderDetail.PriceExVAT)*@
                    Prijs ex BTW
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.orderDetail.VAT.VATValue)*@
                    BTW
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.orderDetail.TotalExVat)*@
                    Tot. ex BTW
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.orderDetail.TotalIncVat)*@
                    Tot. inc BTW
                </th>
                <th>

                </th>
            </tr>

            @foreach (var item in Model.order.OrderDetail)
            {
                <tr>
                    <td class="col-md-1">
                        @item.ProductName
                    </td>
                    <td class="col-md-1">
                        @item.Quantity
                    </td>
                    <td class="col-md-4">
                        @item.Description
                    </td>
                    <td class="col-md-1">
                        @item.PriceExVAT
                    </td>
                    <td class="col-md-1">
                        @item.VAT.VATValue%
                    </td>
                    <td class="col-md-1">
                        @item.TotalExVat
                    </td>
                    <td class="col-md-1">
                        @item.TotalIncVat
                    </td>
                    <td class="col-md-2">
                        <abbr title="Aantal aanpassen">
                            <a href="@Url.Action("Edit", "OrderDetails", new { id = item.OrderDetailId })" class="btn btn-primary">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>
                        </abbr>
                        <abbr title="Artikel verwijderen">
                            <a href="@Url.Action("Delete", "OrderDetails", new { id = item.OrderDetailId })" class="btn btn-danger">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </abbr>
                    </td>
                </tr>
            }
            <tr>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.order.TotalPrice)
                </th>
                <th>
                </th>
            </tr>
            <tr style="border: hidden">
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    @Html.DisplayFor(model => model.order.TotalPrice)
                </td>
            </tr>
        </table>
    }
}


<div style="margin-bottom: 5px;">
    <a href="@Url.Action("Edit", "Orders", new { id = Model.order.OrderId })" class="btn btn-info">
        Ga naar order
    </a>
</div>
@using (Html.BeginForm("Index", "Orders"))
{
    <button type="submit" class="btn btn-info">Ga naar overzicht</button>
}

DeBrabander/Views/Orders/Delete.cshtml
@model DeBrabander.Models.Order

@{
    ViewBag.Title = "De Brabander";}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Annotation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Annotation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CellPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CellPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Box)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Box)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCodeNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCodeNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Town)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DeBrabander/Views/Orders/Details.cshtml
@model DeBrabander.Models.Order

@{
    ViewBag.Title = "De Brabander";}

<h2>Details</h2>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Annotation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Annotation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CellPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CellPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Box)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Box)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCodeNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCodeNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Town)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Town)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OrderId }) |
    @Html.ActionLink("Back to List", "Index")
</p>