DeBrabander/Models/Quotation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DeBrabander.Models
{
    public class Quotation
    {
        public int QuotationID { get; set; }
        [DisplayName("Offerte nummer")]
        public int QuotationNumber { get; set; }
        [DisplayFormat(DataFormatString = "{0:C}")]
        [DisplayName("Totaal prijs")]
        public int TotalPrice { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("Aangemaakt op")]
        public DateTime Date { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("Vervalt op")]
        public DateTime ExpirationDate { get; set; }
        [DisplayName("Opmerking")]
        public string Annotation { get; set; }
        [DisplayName("Actief")]
        public bool Active { get; set; }
        public int CustomerID { get; set; }
        public virtual Customer Customer { get; set; }
    }
}

DeBrabander/ViewModels/Quotations/QuotationAddProductsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DeBrabander.Models;
using PagedList;

namespace DeBrabander.ViewModels.Quotations
{
    public class QuotationAddProductsViewModel
    {
        public Quotation quotation = new Quotation();
        public QuotationDetail quotationDetail = new QuotationDetail();

        // voor lijst producten in add products +
        public IPagedList<Product> products { get; set; }
        public Product product = new Product();
    }
}

DeBrabander/ViewModels/Quotations/QuotationCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DeBrabander.Models;
using PagedList;

namespace DeBrabander.ViewModels.Quotations
{
    public class QuotationCreateViewModel
    {
        public Quotation quotation = new Quotation();
        public IPagedList<Customer> customers { get; set; }
        public Customer customer { get; set; }
    }
}

DeBrabander/Controllers/QuotationDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DeBrabander.DAL;
using DeBrabander.Models;

namespace DeBrabander.Controllers
{
    public class QuotationDetailsController : Controller
    {
        private Context db = new Context();

        // GET: QuotationDetails
        public ActionResult Index()
        {
            return View(db.QuotationDetails.ToList());
        }

        // GET: QuotationDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuotationDetail quotationDetail = db.QuotationDetails.Find(id);
            if (quotationDetail == null)
            {
                return HttpNotFound();
            }
            return View(quotationDetail);
        }

        // GET: QuotationDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuotationDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QuotationDetailId,Quantity,QuotationId,ProductId,ProductName,ProductCode,Description,PriceExVAT,Reprobel,Bebat,Recupel,Auvibel,Brand,CategoryId,VATPercId")] QuotationDetail quotationDetail)
        {
            if (ModelState.IsValid)
            {
                db.QuotationDetails.Add(quotationDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(quotationDetail);
        }

        // GET: QuotationDetails/Edit/5
        public ActionResult Edit(int? id, int? edit)
        {
            ViewBag.VAT = new SelectList(db.VATs, "VATPercId", "VATValue");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuotationDetail quotationDetail = db.QuotationDetails.Find(id);
            if (quotationDetail == null)
            {
                return HttpNotFound();
            }
            // zet de edit waarde op 0 of 1 (zodat we weten dat hij van Edit of vanuit addproducts komt)
            ViewBag.edit = 0;
            if (edit != null)
            {
                ViewBag.edit = edit;
            }
            
            return View(quotationDetail);
        }

        // POST: QuotationDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "QuotationDetailId,Quantity,QuotationId,ProductId,ProductName,ProductCode,Description,PriceExVAT,Reprobel,Bebat,Recupel,Auvibel,Brand,CategoryId,VATPercId")] QuotationDetail quotationDetail, int editValue)
        {
            Product prod = new Product();
            prod = db.Products.Find(quotationDetail.ProductId);

            //aangezien VAT obj niet 100% mee linkt vanuit de edit halen we deze opnieuw op via QD id
            VAT tempqd = db.VATs.Find(quotationDetail.VATPercId);

            quotationDetail.ProductName = prod.ProductName;
            quotationDetail.TotalExVat = (quotationDetail.PriceExVAT + quotationDetail.Auvibel + quotationDetail.Bebat + quotationDetail.Recupel + quotationDetail.Reprobel) * quotationDetail.Quantity;
            quotationDetail.TotalIncVat = quotationDetail.TotalExVat * (1 + (tempqd.VATValue / 100));
            
            if (ModelState.IsValid)
            {
                db.Entry(quotationDetail).State = EntityState.Modified;
                db.SaveChanges();
                if (editValue == 1)
                {
                    return RedirectToAction("Edit", "Quotations", new { id = quotationDetail.QuotationId });
                }
                return RedirectToAction("AddProducts", "Quotations", new { id = quotationDetail.QuotationId });
            }
            return View(quotationDetail);
        }

        // GET: QuotationDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuotationDetail quotationDetail = db.QuotationDetails.Find(id);
            if (quotationDetail == null)
            {
                return HttpNotFound();
            }
            // uitleg returnUrl http://stackoverflow.com/questions/9772947/c-sharp-asp-net-mvc-return-to-previous-page
            ViewBag.returnUrl = Request.UrlReferrer;
            return View(quotationDetail);
        }

        // POST: QuotationDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, string returnUrl)
        {
            QuotationDetail quotationDetail = db.QuotationDetails.Find(id);
            db.QuotationDetails.Remove(quotationDetail);

            db.SaveChanges();
            return Redirect(returnUrl);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DeBrabander/Controllers/QuotationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using DeBrabander.DAL;
using DeBrabander.Models;
using DeBrabander.ViewModels.Quotations;
using DeBrabander.ViewModels;
using CrystalDecisions.CrystalReports.Engine;
using PagedList;
using System.IO;

namespace DeBrabander.Controllers
{
    public class QuotationBinderCreate : IModelBinder
    {
        //private Context db2 = new Context();
        public object BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
        {
            HttpContextBase objContext = controllerContext.HttpContext;            
            QuotationCreateViewModel obj = new QuotationCreateViewModel();
            obj.quotation.Annotation = objContext.Request.Form["QuotationInfo"];
            return obj;
        }
    }


    //ActionNameSelectorAttribute
    public class SubmitButton : ActionNameSelectorAttribute
    {
        public string Name { get; set; }
        public override bool IsValidName(ControllerContext controllerContext, string actionName, MethodInfo methodInfo)
        {
            var value = controllerContext.Controller.ValueProvider.GetValue(Name);
            if (value == null)
            {
                return false;
            }
            return true;
        }
    }

    public class QuotationsController : Controller
    {
        private Context db = new Context();

        // GET: Quotations
        public ActionResult Index(string searchQuotationNumber, string currentFilterQuotationNumber ,string searchCustomer, string currentFilterCustomer,string searchDelivery, string currentFilterDelivery, bool? searchNonActive, bool? currentFilterNonActive, int? page, string sortOrder)
        {
            // viewmodel aanmaken + vullen tijdelijke lijst
            if (searchNonActive == null) { searchNonActive = false; }
            if (currentFilterNonActive == null) { currentFilterNonActive = false; }
            QuotationIndexViewModel qivm = new QuotationIndexViewModel();
            var quotations = from q in db.Quotations select q;
            Quotation quot = new Quotation();


            ViewBag.Error =  TempData["error"];
            //ViewBag.CurrentSort = sortOrder;


            ViewBag.QuotationSortParm = String.IsNullOrEmpty(sortOrder) ? "quot_asc" : "";
            ViewBag.CustomerSortParm = sortOrder=="cust" ? "cust_desc" : "cust";


            if (searchCustomer != null || searchQuotationNumber !=null)
            {
                page = 1;
            }
            else
            {
                searchQuotationNumber = currentFilterQuotationNumber;
                searchCustomer = currentFilterCustomer;
                searchDelivery = currentFilterDelivery;
                searchNonActive = currentFilterNonActive;
            }
            ViewBag.CurrentFilterQuotation = searchQuotationNumber;
            ViewBag.CurrentFilterCustomer = searchCustomer;
            ViewBag.CurrentFilterDelivery = searchDelivery;
            ViewBag.CurrentFilterNonActive = searchNonActive;


            if (!String.IsNullOrEmpty(searchQuotationNumber))
            {
                quotations = quotations.Where(q => q.QuotationNumber.ToString().Contains(searchQuotationNumber));
            }
            if (!String.IsNullOrEmpty(searchCustomer))
            {
                quotations = quotations.Where(q => q.LastName.ToUpper().Contains(searchCustomer.ToUpper()) || q.FirstName.ToUpper().Contains(searchCustomer.ToUpper()));
            }
            if (!string.IsNullOrEmpty(searchDelivery))
            {
                quotations = quotations.Where(q => q.customerDeliveryAddress.DeliveryAddressInfo.ToUpper().Contains(searchDelivery.ToUpper()) || q.customerDeliveryAddress.StreetName.ToUpper().Contains(searchDelivery.ToUpper()) || q.customerDeliveryAddress.Town.ToUpper().Contains(searchDelivery.ToUpper()));
            }

           
            switch(sortOrder)
            {
                case "quot_asc":
                    quotations = quotations.OrderBy(s => s.QuotationNumber);
                    break;
                case "cust_desc":
                    quotations = quotations.OrderByDescending(s => s.LastName);
                    break;
                case "cust":
                    quotations = quotations.OrderBy(s => s.LastName);
                    break;
                default:
                    quotations = quotations.OrderByDescending(s => s.QuotationNumber);
                    break;
            }

            var userDefinedInfo = db.UserDefinedSettings.Find(1);
            int pageSize = userDefinedInfo.IndexResultLength;
            int pageNumber = (page ?? 1);

            if (searchNonActive == false ||searchNonActive == null)
            {
                quotations = quotations.Where(q => q.Active.Equals(true));
            }


            //ViewBag.Quotations = quotations.ToPagedList(pageNumber, pageSize);
            qivm.quotations = quotations.ToPagedList(pageNumber, pageSize);

            return View(qivm);
        }

        // GET: Quotations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quotation quotation = db.Quotations.Find(id);
            if (quotation == null)
            {
                return HttpNotFound();
            }
            return View(quotation);
        }

        // GET: Quotations/Create
        public ActionResult Create(string sortOrder, string searchStringName, string searchStringTown, string currentFilterName, string currentFilterTown, int? page)
        {
            // quotation viewmodel + ipaged list users aanmaken + nieuwe quotation voor default stuff
            QuotationCreateViewModel qcvm = new QuotationCreateViewModel();
            var customerList = from a in db.Customers select a;
            Quotation quotation = new Quotation();

            DefaultQuotationInfo(quotation);
               
            qcvm.quotation = quotation;


            //zoeken / sorteren / paging
            //sorteren  default op "name_desc" 
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.TownSortParm = sortOrder == "town" ? "town_desc" : "town";


            // als zoeken leeg is pagina 1 anders 
            if (searchStringTown != null || searchStringName != null)
            {
                page = 1;
            }
            else
            {
                searchStringName = currentFilterName;
                searchStringTown = currentFilterTown;
            }
            ViewBag.CurrentFilterName = searchStringName;
            ViewBag.CurrentFilterTown = searchStringTown;



            // zoekvelden toepassen op klantenlijst
            //zoeken op naam (voor of achter en/of gemeente)           
            if (!String.IsNullOrEmpty(searchStringTown))
            {
                customerList = customerList.Where(s => s.Address.Town.ToUpper().Contains(searchStringTown.ToUpper()));
            }

            // zoeken op postalcode
            if (!String.IsNullOrEmpty(searchStringName))
            {
                customerList = customerList.Where(s => s.LastName.ToUpper().Contains(searchStringName.ToUpper()) ||
                s.FirstName.ToUpper().Contains(searchStringName.ToUpper()));
            }


            switch (sortOrder)
            {
                case "name_desc":
                    customerList = customerList.OrderByDescending(s => s.LastName);
                    break;
                case "town":
                    customerList = customerList.OrderBy(s => s.Address.Town);
                    break;
                case "town_desc":
                    customerList = customerList.OrderByDescending(s => s.Address.Town);
                    break;
                default:
                    customerList = customerList.OrderBy(s => s.LastName);
                    break;
            }

            var userDefinedInfo = db.UserDefinedSettings.Find(1);
            int pageSize = userDefinedInfo.DetailsResultLength;
            int pageNumber = (page ?? 1);

            qcvm.customers = customerList.ToPagedList(pageNumber, pageSize);


            return View(qcvm);
        }



        // POST: Quotations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SubmitButton(Name = "Create")]
        public ActionResult Create([ModelBinder(typeof(QuotationBinderCreate))]  QuotationCreateViewModel qcvm, string[] DeliveryID)
        {
            if (ModelState.IsValid)
            {
                //aanmaken van quotation / customerdeliveryaddress en customer
                Quotation quotation = new Quotation();
                CustomerDeliveryAddress cda = new CustomerDeliveryAddress();
                Customer cus = new Customer();

                //ophalen van customerDeliveryAddressID vanuit de array
                // eventueel nog test inbouwen voor lengte van array (check dat ze niet meer als 1 veld selecteren)
                int DeliveryId = 1;
                if (DeliveryID.Length == 1)
                {
                    DeliveryId = Int32.Parse(DeliveryID.First());
                }
                else
                {
                   return RedirectToAction("Create");
                }

                // ophalen delivery info en van daaruit customer info
                cda = db.CustomerDeliveryAddresses.Find(DeliveryId);
                cus = db.Customers.Find(cda.CustomerId);

                // invullen van de klant info in de quotation

DeBrabander/Views/Quotations/AddProducts.cshtml
@model DeBrabander.ViewModels.Quotations.QuotationAddProductsViewModel
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "De Brabander";
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Site.css" rel="stylesheet" />
<h2>Artikelen toevoegen op offerte van @Model.quotation.FullName</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div>
        @using (Html.BeginForm("AddProducts", "Quotations", FormMethod.Get, new { id = Model.quotation.QuotationId }))
        {
            <p>
                @Html.TextBox("searchString", ViewBag.CurrentFilterSearchString as string, new { @class = "form-control", placeholder = "Zoeken op productnaam/code", @style = "margin: 3px;" })
                @Html.DropDownList("CategoryID", (SelectList)ViewBag.CategoryID, "Categorie", new {@class="btn btn-default dropdown-toggle"})
                @Html.TextBox("id", Model.quotation.QuotationId, new { @class = "hidden" })
                <input type="submit" value="Zoek" class="btn btn-default" style="margin: 3px" />
            </p>
        }
    </div>

    <table class="table table-striped">
        <tr>
            <th>
                @Html.ActionLink(Html.DisplayNameFor(Model => Model.product.ProductName).ToHtmlString(), "addProduct", new { sortOrder = ViewBag.ProductSortParm })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.ProductCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.PriceExVAT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.Category.CategoryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.Description)
            </th>
            <th>

            </th>
        </tr>

        @if (Model.products.Count() == 0)
        {
            <tr>
                <td colspan="3">Er voldoen geen artikelen aan je zoekopdracht</td>
            </tr>
        }
        else
        {
            foreach (var item in Model.products)
            {
                <tr>
                    <td>

                        @item.ProductName
                    </td>
                    <td>
                        @item.ProductCode
                    </td>
                    <td>
                        @item.Brand
                    </td>
                    <td>
                        @item.PriceExVAT
                    </td>
                    <td>
                        @item.Category.CategoryName
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        <abbr title="Artikel toevoegen">
                            <a href="@Url.Action("AddProductToQuotation", "Quotations", new { productId = item.ProductId, quotationId = Model.quotation.QuotationId })" class="btn btn-success">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            </a>
                        </abbr>

                    </td>

                </tr>
            }
        }
    </table>
}

<div class="row">
    <div class="col-md-2 col-md-offset-10">
        Pagina @(Model.products.PageCount < Model.products.PageNumber ? 0 : Model.products.PageNumber) van de @Model.products.PageCount
    </div>
    <div class="col-md-2 col-md-offset-10">
        @Html.PagedListPager(Model.products, page => Url.Action("AddProducts", new { @class = "pagination pagination-sm", page, currentFilterSearchString = ViewBag.CurrentFilterSearchString, currentFilterCategoryId = ViewBag.CurrentFilterCategoryId }), PagedList.PagedListRenderOptions.tomsLayout)
    </div>
</div>
<div>
    <table align="center"></table>
</div>

<br />
<br />

@if (Model != null)
{
    if (Model.quotation.QuotationDetail != null && Model.quotation.QuotationDetail.Count != 0)
    {
        <table class="table table-striped">
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.quotationDetail.ProductName)*@
                    Artikel
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.quotationDetail.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.quotationDetail.Description)
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.quotationDetail.PriceExVAT)*@
                    Prijs ex BTW
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.quotationDetail.VAT.VATValue)*@
                    BTW
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.quotationDetail.TotalExVat)*@
                    Tot. ex BTW
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.quotationDetail.TotalIncVat)*@
                    Tot. inc BTW
                </th>
                <th>

                </th>
            </tr>

            @foreach (var item in Model.quotation.QuotationDetail)
            {
                <tr>
                    <td class="col-md-1">
                        @item.ProductName
                    </td>
                    <td class="col-md-1">
                        @item.Quantity
                    </td>
                    <td class="col-md-4">
                        @item.Description
                    </td>
                    <td class="col-md-1">
                        @item.PriceExVAT
                    </td>
                    <td class="col-md-1">
                        @item.VAT.VATValue%
                    </td>
                    <td class="col-md-1">
                        @item.TotalExVat
                    </td>
                    <td class="col-md-1">
                        @item.TotalIncVat
                    </td>
                    <td class="col-md-2">
                        <abbr title="Aantal aanpassen">
                            <a href="@Url.Action("Edit", "QuotationDetails", new { id = item.QuotationDetailId })" class="btn btn-primary">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                            </a>
                        </abbr>
                        <abbr title="Artikel verwijderen">
                            <a href="@Url.Action("Delete", "QuotationDetails", new { id = item.QuotationDetailId })" class="btn btn-danger">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </abbr>
                    </td>
                </tr>
            }
            <tr>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.quotation.TotalPrice)
                </th>
                <th>
                </th>
            </tr>
            <tr style="border: hidden">
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    @Html.DisplayFor(model => model.quotation.TotalPrice)
                </td>
                <td></td>
            </tr>
        </table>
    }
}


<div style="margin-bottom: 5px;">
    <a href="@Url.Action("Edit", "Quotations", new { id = Model.quotation.QuotationId })" class="btn btn-info">
        Ga naar offerte
    </a>
</div>
@using (Html.BeginForm("Index", "Quotations"))
{
    <button type="submit" class="btn btn-info">Ga naar overzicht</button>
}

DeBrabander/Views/Quotations/Delete.cshtml
@model DeBrabander.Models.Quotation

@{
    ViewBag.Title = "De Brabander";
}

<h2>Offerte verwijderen</h2>

<h3>Bent u zeker dat u deze offerte wil verwijderen?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuotationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuotationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Annotation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Annotation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-info" /> 
            <a href="@Url.Action("Index", "Quotations")" class="btn btn-info">Sluiten</a>
         
        </div>
    }
</div>

DeBrabander/Views/Quotations/Details.cshtml
@model DeBrabander.Models.Quotation

@{
    ViewBag.Title = "De Brabander";
}

<h2>Details</h2>

<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QuotationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuotationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExpirationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Annotation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Annotation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Aanpassen", "Edit", new { id = Model.QuotationId }) |
    @Html.ActionLink("Offerte overzicht", "Index")
</p>