DeBrabander/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DeBrabander.DAL;
using DeBrabander.Models;
using DeBrabander.ViewModels.Orders;
using DeBrabander.ViewModels;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;
using PagedList;

namespace DeBrabander.Controllers
{
    public class OrderBinderCreate : IModelBinder
    {
        //private Context db2 = new Context();
        public object BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
        {
            HttpContextBase objContext = controllerContext.HttpContext;
            OrderCreateViewModel obj = new OrderCreateViewModel();
            obj.order.Annotation = objContext.Request.Form["OrderInfo"];
            return obj;
        }
    }

    public class OrdersController : Controller
    {
        private Context db = new Context();

        // GET: Orders
        public ActionResult Index(string searchOrderNumber, string currentFilterOrderNumber, string searchCustomer, string currentFilterCustomer, string searchDelivery, string currentFilterDelivery, bool? searchNonActive, bool? currentFilterNonActive, int? page, string sortOrder)
        {
            // viewmodel aanmaken + vullen tijdelijke lijst
            if (searchNonActive == null) { searchNonActive = false; }
            if (currentFilterNonActive == null) { currentFilterNonActive = false; }
            OrderIndexViewModel oivm = new OrderIndexViewModel();
            var orders = from o in db.Orders select o;
            Order order = new Order();

            
            ViewBag.OrderSortParm = String.IsNullOrEmpty(sortOrder) ? "order_asc" : "";
            ViewBag.CustomerSortParm = sortOrder == "cust" ? "cust_desc" : "cust";


            if (searchCustomer != null || searchOrderNumber != null)
            {
                page = 1;
            }
            else
            {
                searchOrderNumber = currentFilterOrderNumber;
                searchCustomer = currentFilterCustomer;
                searchDelivery = currentFilterDelivery;
                searchNonActive = currentFilterNonActive;
            }
            ViewBag.CurrentFilterQuotation = searchOrderNumber;
            ViewBag.CurrentFilterCustomer = searchCustomer;
            ViewBag.CurrentFilterDelivery = searchDelivery;
            ViewBag.CurrentFilterNonActive = searchNonActive;


            if (!String.IsNullOrEmpty(searchOrderNumber))
            {
                orders = orders.Where(o => o.OrderNumber.ToString().Contains(searchOrderNumber));
            }
            if (!String.IsNullOrEmpty(searchCustomer))
            {
                orders = orders.Where(o => o.LastName.ToUpper().Contains(searchCustomer.ToUpper()) || o.FirstName.ToUpper().Contains(searchCustomer.ToUpper()));
            }
            if (!string.IsNullOrEmpty(searchDelivery))
            {
                orders = orders.Where(o => o.customerDeliveryAddress.DeliveryAddressInfo.ToUpper().Contains(searchDelivery.ToUpper()) || o.customerDeliveryAddress.StreetName.ToUpper().Contains(searchDelivery.ToUpper()) || o.customerDeliveryAddress.Town.ToUpper().Contains(searchDelivery.ToUpper()));
            }


            switch (sortOrder)
            {
                case "order_asc":
                    orders = orders.OrderBy(o => o.OrderNumber);
                    break;
                case "cust_desc":
                    orders = orders.OrderByDescending(o => o.LastName);
                    break;
                case "cust":
                    orders = orders.OrderBy(o => o.LastName);
                    break;
                default:
                    orders = orders.OrderByDescending(o => o.OrderNumber);
                    break;
            }

            var userDefinedInfo = db.UserDefinedSettings.Find(1);
            int pageSize = userDefinedInfo.IndexResultLength;
            int pageNumber = (page ?? 1);

            if (searchNonActive == false || searchNonActive == null)
            {
                orders = orders.Where(o => o.Active.Equals(true));
            }


            //ViewBag.Quotations = quotations.ToPagedList(pageNumber, pageSize);
            oivm.orders = orders.ToPagedList(pageNumber, pageSize);

            return View(oivm);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create(string sortOrder, string searchStringName, string searchStringTown, string currentFilterName, string currentFilterTown, int? page)
        {
            // quotation viewmodel + ipaged list users aanmaken + nieuwe quotation voor default stuff
            OrderCreateViewModel ocvm = new OrderCreateViewModel();
            var customerList = from a in db.Customers select a;
            Order order = new Order();

            DefaultOrderInfo(order);

            ocvm.order = order;


            //zoeken / sorteren / paging
            //sorteren  default op "name_desc" 
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.TownSortParm = sortOrder == "town" ? "town_desc" : "town";


            // als zoeken leeg is pagina 1 anders 
            if (searchStringTown != null || searchStringName != null)
            {
                page = 1;
            }
            else
            {
                searchStringName = currentFilterName;
                searchStringTown = currentFilterTown;
            }
            ViewBag.CurrentFilterName = searchStringName;
            ViewBag.CurrentFilterTown = searchStringTown;



            // zoekvelden toepassen op klantenlijst
            //zoeken op naam (voor of achter en/of gemeente)           
            if (!String.IsNullOrEmpty(searchStringTown))
            {
                customerList = customerList.Where(s => s.Address.Town.ToUpper().Contains(searchStringTown.ToUpper()));
            }

            // zoeken op postalcode
            if (!String.IsNullOrEmpty(searchStringName))
            {
                customerList = customerList.Where(s => s.LastName.ToUpper().Contains(searchStringName.ToUpper()) ||
                s.FirstName.ToUpper().Contains(searchStringName.ToUpper()));
            }


            switch (sortOrder)
            {
                case "name_desc":
                    customerList = customerList.OrderByDescending(s => s.LastName);
                    break;
                case "town":
                    customerList = customerList.OrderBy(s => s.Address.Town);
                    break;
                case "town_desc":
                    customerList = customerList.OrderByDescending(s => s.Address.Town);
                    break;
                default:
                    customerList = customerList.OrderBy(s => s.LastName);
                    break;
            }

            var userDefinedInfo = db.UserDefinedSettings.Find(1);
            int pageSize = userDefinedInfo.DetailsResultLength;
            int pageNumber = (page ?? 1);

            ocvm.customers = customerList.ToPagedList(pageNumber, pageSize);


            return View(ocvm);
        }

        private Order DefaultOrderInfo(Order order)
        {
            //basis info invullen in order
            //ophalen van lijst orders voor vinden van laatste ordernummer en dan +1 
            var listOrders = new List<Order>();
            listOrders = db.Orders.ToList();
            var userSettings = db.UserDefinedSettings.Find(1);
            

            int maxOrdernumber = 1;
            order.OrderNumber = maxOrdernumber;
            if (listOrders.Count != 0)
            {
                maxOrdernumber = listOrders.Max(o => o.OrderNumber);
                order.OrderNumber = maxOrdernumber + 1;
            }
            order.Active = true;
            order.Date = DateTime.Now;            

            return order;
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [SubmitButton(Name ="CreateOrder")]
        public ActionResult Create([ModelBinder(typeof(OrderBinderCreate))]  OrderCreateViewModel ocvm, string[] DeliveryID)
        {
            if (ModelState.IsValid)
            {
                //aanmaken van quotation / customerdeliveryaddress en customer
                Order order  = new Order();
                CustomerDeliveryAddress cda = new CustomerDeliveryAddress();
                Customer cus = new Customer();

                //ophalen van customerDeliveryAddressID vanuit de array
                // eventueel nog test inbouwen voor lengte van array (check dat ze niet meer als 1 veld selecteren)
                int DeliveryId = 1;
                if (DeliveryID.Length == 1)
                {
                    DeliveryId = Int32.Parse(DeliveryID.First());
                }
                else
                {
                    return RedirectToAction("Create");
                }

                // ophalen delivery info en van daaruit customer info
                cda = db.CustomerDeliveryAddresses.Find(DeliveryId);
                cus = db.Customers.Find(cda.CustomerId);

                // invullen van de klant info in de quotation
                DefaultOrderInfo(order);
                order.FirstName = cus.FirstName;

DeBrabander/Controllers/SettingsController.cs
using DeBrabander.DAL;
using DeBrabander.ViewModels.Settings;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeBrabander.Controllers
{
    public class SettingsController : Controller
    {
        private Context db = new Context();
        // GET: Settings
        public ActionResult Index()
        {
            SettingsViewModel svm = new SettingsViewModel();
          
            return View(svm);
        }

       
    }
}

DeBrabander/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeBrabander.Models;
using DeBrabander.DAL;
using DeBrabander.Utils;

namespace DeBrabander.Controllers
{
    public class UserAccountController : Controller
    {
        // GET: UserAccount
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserAccount account)
        {
            if (ModelState.IsValid)
            {
                using (Context db = new Context())
                {
                    account.Password = SecurityUtil.hashPassword(account.Password);
                    account.ConfirmPassword = SecurityUtil.hashPassword(account.ConfirmPassword);
                    db.UserAccounts.Add(account);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = account.FirstName + " " + account.LastName + "Registratie is voltooid.";
            }
            return View();
        }

        //login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login (UserAccount user)
        {
            using (Context db = new Context())
            {
                var usr = db.UserAccounts.Where(u => u.Username == user.Username).FirstOrDefault();
                if (usr != null && usr.Password == SecurityUtil.hashPassword(user.Password))
                {
                    Session["UserID"] = usr.UserID.ToString();
                    Session["Gebruikersnaam"] = usr.Username.ToString();
                    return RedirectToAction("LoggedIn");
                }
                else
                {
                    ModelState.AddModelError("", "Gebruikersnaam of wachtwoord zijn fout");
                }
            }
            return View();
        }

        public ActionResult LoggedIn()
        {
            if (Session["UserID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
    }
}

DeBrabander/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("favicon.ico")" rel="icon" type="image/x-icon" />
  
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("De Brabander", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @* dropdown menu voor klanten *@
                    <li class="dropdown">
                        <a href="#" dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="true">Klanten</a>
                        <ul class="dropdown-menu" role="menu" id="myTab">
                            <li role="presentation">
                                <a href="@Url.Action("Index", "Customers")">Overzicht Klanten</a>
                            </li>
                            <li role="presentation">
                                <a href="@Url.Action("Create", "Customers")">Nieuwe Klant Aanmaken</a>
                            </li>
                        </ul>
                    </li>
                    @* Dropdown voor offertes *@
                    <li class="dropdown">
                        <a href="#" dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">Offertes</a>
                        <ul class="dropdown-menu" role="menu" id="myTab">
                            <li role="presentation">
                                <a href="@Url.Action("Index", "Quotations")">Overzicht Offertes</a>
                            </li>
                            <li role="presentation">
                                <a href="@Url.Action("Create", "Quotations")">Nieuwe Offerte Aanmaken</a>
                            </li>
                        </ul>
                    </li>
                    @* Dropdown voor orders *@
                    <li class="dropdown">
                        <a href="#" dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">Orders</a>
                        <ul class="dropdown-menu" role="menu" id="myTab">
                            <li role="presentation">
                                <a href="@Url.Action("Index", "Orders")">Overzicht Orders</a>
                            </li>
                            <li role="presentation">
                                <a href="@Url.Action("Create", "Orders")">Nieuwe order Aanmaken</a>
                            </li>
                        </ul>
                    </li>



                    @* Dropdown voor facturen *@
                    <li class="dropdown">
                        <a href="#" dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">Facturen</a>
                        <ul class="dropdown-menu" role="menu" id="myTab">
                            <li role="presentation">
                                <a href="@Url.Action("Index", "Invoices")">Overzicht Facturen</a>
                            </li>
                        </ul>
                    </li>
                    @* Dropdown voor artikels *@
                    <li class="dropdown">
                        <a href="#" dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">Artikelen</a>
                        <ul class="dropdown-menu" role="menu" id="myTab">
                            <li role="presentation">
                                <a href="@Url.Action("Index", "Products")">Overzicht Artikelen</a>
                            </li>
                            <li role="presentation">
                                <a href="@Url.Action("Create", "Products")">Nieuw Artikel Aanmaken</a>
                            </li>
                        </ul>
                    </li>
                    @* Dropdown voor login *@
                    @*<li class="dropdown">
                        <a href="#" dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">Aanmelden</a>
                        <ul class="dropdown-menu" role="menu" id="myTab">
                            <li role="presentation">
                                <a href="@Url.Action("Login", "UserAccount")">Aanmelden</a>
                            </li>
                            <li role="presentation">
                                <a href="@Url.Action("Register", "UserAccount")">Nieuwe Gebruiker Aanmaken</a>
                            </li>
                        </ul>
                    </li>*@
                 </ul>
                <ul class="nav navbar-nav navbar-right">
                    @*FAQ*@
                    <li>@Html.ActionLink("FAQ", "FAQ", "FAQ")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @*Instellingen*@
                    <li>@Html.ActionLink("Instellingen", "Index", "Settings")</li>
                </ul>
             

                </div>  
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - De Brabander bvba</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>