DeBrabander/Models/Products/VAT.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DeBrabander.Models
{
    public class VAT
    {
        [Key]
        public int VATPercId { get; set; }

        [DisplayName("BTW %")]
        public double VATValue { get; set; }
    }
}

DeBrabander/ViewModels/Vats/VatCreateViewModel.cs
using DeBrabander.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeBrabander.ViewModels.VATs
{
    public class VatCreateViewModel
    {
        public int VATPercId { get; set; }

        [DisplayName("BTW %")]
        public double VATValue { get; set; }
    }

}

DeBrabander/ViewModels/Vats/VatDetailsViewModel.cs
using DeBrabander.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeBrabander.ViewModels.VATs
{
    public class VatDetailsViewModel
    {
        public int VATPercId { get; set; }

        [DisplayName("BTW")]
        public double VATValue { get; set; }
    }

}

DeBrabander/ViewModels/Vats/VatEditViewModel.cs
using DeBrabander.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeBrabander.ViewModels.VATs
{
    public class VatEditViewModel
    {
        public int VATPercId { get; set; }

        [DisplayName("BTW %")]
        public double VATValue { get; set; }
    }

}

DeBrabander/ViewModels/Vats/VatIndexViewModel.cs
using DeBrabander.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeBrabander.ViewModels.VATs
{
    public class VatIndexViewModel
    {
        public int VATPercId { get; set; }

        [DisplayName("BTW")]
        public double VATValue { get; set; }

        public VAT vat = new VAT();
    }

}

DeBrabander/Controllers/SettingsController.cs
using DeBrabander.DAL;
using DeBrabander.ViewModels.Settings;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeBrabander.Controllers
{
    public class SettingsController : Controller
    {
        private Context db = new Context();
        // GET: Settings
        public ActionResult Index()
        {
            SettingsViewModel svm = new SettingsViewModel();
          
            return View(svm);
        }

       
    }
}

DeBrabander/Controllers/VATsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DeBrabander.DAL;
using DeBrabander.Models;
using DeBrabander.ViewModels.VATs;

namespace DeBrabander.Controllers
{
    public class VATsController : Controller
    {
        private Context db = new Context();

        // GET: VATs
        public ActionResult Index()
        {
            List<VatIndexViewModel> VATVMList = new List<VatIndexViewModel>();
            List<VAT> vats = new List<VAT>(db.VATs.ToList());

            foreach (var vat in vats)
            {
                VatIndexViewModel vivm = new VatIndexViewModel();
                vivm.VATPercId = vat.VATPercId;
                vivm.VATValue = vat.VATValue;
                VATVMList.Add(vivm);
            }
            return View(VATVMList);
        }

        // GET: VATs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VAT vAT = db.VATs.Find(id);
            if (vAT == null)
            {
                return HttpNotFound();
            }
            VatDetailsViewModel vdvm = new VatDetailsViewModel();
            vdvm.VATPercId = vAT.VATPercId;
            vdvm.VATValue = vAT.VATValue;

            return View(vdvm);
        }

        // GET: VATs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VATs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VATPercId,VATValue")] VatCreateViewModel vatcvm)
        {
            if (ModelState.IsValid)
            {
                VAT vat = new VAT();
                vat.VATValue = vatcvm.VATValue;

                db.VATs.Add(vat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(vatcvm);
        }

        // GET: VATs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VAT vAT = db.VATs.Find(id);
            VatEditViewModel vevm = new VatEditViewModel();
            vevm.VATPercId = vAT.VATPercId;
            vevm.VATValue = vAT.VATValue;

            if (vAT == null)
            {
                return HttpNotFound();
            }
            return View(vevm);
        }

        // POST: VATs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VATPercId,VATValue")] VatCreateViewModel vatcvm)
        {
            if (ModelState.IsValid)
            {
                VAT vat = new VAT();
                vat.VATPercId = vatcvm.VATPercId;
                vat.VATValue = vatcvm.VATValue;


                db.Entry(vat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vatcvm);
        }

        // GET: VATs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VAT vAT = db.VATs.Find(id);
            if (vAT == null)
            {
                return HttpNotFound();
            }
            return View(vAT);
        }

        // POST: VATs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VAT vAT = db.VATs.Find(id);
            db.VATs.Remove(vAT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DeBrabander/Views/VATs/Create.cshtml
@model DeBrabander.ViewModels.VATs.VatCreateViewModel

@{
    ViewBag.Title = "De Brabander";
}

<h2>Tarief aanmaken</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.VATValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VATValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VATValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-info" />
                <a href="@Url.Action("Index", "Vats")" class="btn btn-info">Sluiten</a>
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DeBrabander/Views/VATs/Delete.cshtml
@model DeBrabander.Models.VAT

@{
    ViewBag.Title = "De Brabander";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VAT</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VATValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VATValue)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DeBrabander/Views/VATs/Edit.cshtml
@model DeBrabander.ViewModels.VATs.VatEditViewModel

@{
    ViewBag.Title = "De Brabander";
}

<h2>Tarief aanpassen</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VATPercId)

        <div class="form-group">
            @Html.LabelFor(model => model.VATValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VATValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VATValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-info" />
                <a href="@Url.Action("Index", "Vats")" class="btn btn-info">Sluiten</a>
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DeBrabander/Views/VATs/Index.cshtml
@model IEnumerable<DeBrabander.ViewModels.VATs.VatIndexViewModel>

@{
    ViewBag.Title = "De Brabander";
}

<h2>BTW</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.VATValue)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.VATValue)
        </td>
        <td>
            @Html.ActionLink("Aanpassen", "Edit", new { id=item.VATPercId })    
        </td>
    </tr>
}

</table>
<a href="@Url.Action("Create", "VATs")" class="btn btn-info">Tarief aanmaken</a>
<a href="@Url.Action("Index", "Settings")" class="btn btn-info">Sluiten</a>